### ISSUE TITLE
[GA1]Create github action - CI/CD

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#158]
Create a GitHub action, when pR is created it automatically checks.

**Comment by Aayush987** [comment]
Hi, i am interested in this issue. Can you tell me what it needs to check. Like what checks it need to successfully run?

**Comment by Aayush987** [comment]
> Hi, i am interested in this issue. Can you tell me what it needs to check. Like what checks it need to successfully run?

Also please assign this issue to me. I will work on this issue.

**Comment by anmode** [comment]
I have assigned one. Please first complete that. then I'll assign this to you!

**Comment by Aayush987** [comment]
> I have assigned one. Please first complete that. then I'll assign this to you!

OK, thank you.

**Comment by singh-anushka** [comment]
Please assign me this issue. I would like to work on this.

**Comment by shraddha761** [comment]
@anmode request to assign me this issue

**Comment by singh-anushka** [comment]
@shraddha761 ohk no problem. Can you please give a little detail about the issue? So that I can see if any other repository needs this. I can create a pull request there, and improve their code and repository.

**Comment by shraddha761** [comment]
@singh-anushka if you know about devops then only you can do it

**Comment by singh-anushka** [comment]
> @singh-anushka if you know about devops then only you can do it

I know how to add a GitHub action but I don't understand what is actually required to do in this issue. Like which GitHub action, what a GitHub action must do. 
Checking of PRs in terms of what, that I don't understand. Can you please explain me this, I really want to work on this issue.

**Comment by anmode** [comment]
So here....it is look 
```
name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy application
        run: |
          echo "Deploying application to production..."
          ssh root@production-server "mkdir -p /var/www/app"
          tar -czf app.tar.gz ./build
          scp app.tar.gz root@production-server:/var/www/app
          ssh root@production-server "cd /var/www/app && tar -xzf app.tar.gz && rm app.tar.gz"
          ssh root@production-server "systemctl restart nginx"
```
